spring.application.name=backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.profiles.active=local
spring.jpa.hibernate.ddl-auto=create

jwt.secret=${JWT_SECRET}
jwt.access-token-validity-ms=${JWT_ACCESS_TOKEN_VALIDITY_MS:3600000}